spring.application.name=musictracker
spring.datasource.url=jdbc:sqlite:musictracker.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.maximum-pool-size=1
spring.sql.init.mode=always
